// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbAeBSvjbetqIwfdQM6JCv_Q0jgRg14ZM',
    appId: '1:764603990195:web:750f9f9e9260f10f8d30c6',
    messagingSenderId: '764603990195',
    projectId: 'bulutbilisimodev-8b11b',
    authDomain: 'bulutbilisimodev-8b11b.firebaseapp.com',
    storageBucket: 'bulutbilisimodev-8b11b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBurt347b_u-eWYd4esykKW0YWNDdst4qc',
    appId: '1:764603990195:android:a903f2e099b33aa88d30c6',
    messagingSenderId: '764603990195',
    projectId: 'bulutbilisimodev-8b11b',
    storageBucket: 'bulutbilisimodev-8b11b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCttyzDgtUC_E6v2WYhM13E6TDyQba9NC0',
    appId: '1:764603990195:ios:2c50546c4b7a6de18d30c6',
    messagingSenderId: '764603990195',
    projectId: 'bulutbilisimodev-8b11b',
    storageBucket: 'bulutbilisimodev-8b11b.firebasestorage.app',
    iosBundleId: 'com.example.bulutBilisimOdevUygulamasi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCttyzDgtUC_E6v2WYhM13E6TDyQba9NC0',
    appId: '1:764603990195:ios:2c50546c4b7a6de18d30c6',
    messagingSenderId: '764603990195',
    projectId: 'bulutbilisimodev-8b11b',
    storageBucket: 'bulutbilisimodev-8b11b.firebasestorage.app',
    iosBundleId: 'com.example.bulutBilisimOdevUygulamasi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbAeBSvjbetqIwfdQM6JCv_Q0jgRg14ZM',
    appId: '1:764603990195:web:0124b32850fc65488d30c6',
    messagingSenderId: '764603990195',
    projectId: 'bulutbilisimodev-8b11b',
    authDomain: 'bulutbilisimodev-8b11b.firebaseapp.com',
    storageBucket: 'bulutbilisimodev-8b11b.firebasestorage.app',
  );

}